export const endpoint = "https://gist.githubusercontent.com/Pinois/e1c72b75917985dc77f5c808e876b67f/raw/93debb7463fbaaec29622221b8f9e719bd5b119f/birthdayPeople.json";
export const buttonAdd = document.querySelector('.btn-add');
export const modalOuter = document.querySelector('.modal_outer');
export const modalInner = document.querySelector('.modal_inner');
export const tbody = document.querySelector('#lists_container');
export const filterNameInput = document.querySelector("#search_name");
export const filterMonthBirthday = document.querySelector("#month_birthday");
export const filterForm = document.querySelector('.form_filter');
// export const resetBtn = document.querySelector('.reset_filter');